language: python

matrix:
  include:
    - python: 3.4
      dist: trusty
      sudo: false
    - python: 3.5
      dist: trusty
      sudo: false
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.6
      dist: xenial
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: false


# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest